name: mobx_samples
description: MobX Code Samples

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Needed dependencies
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  get_it: ^4.0.4 # If you need to have global state, add this dependency.
                 # With it, we can get an object at any place.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Needed dependencies
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/global_state_sample/
    - images/previews/